// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file api/v1/audit.proto (package api.v1, syntax proto3)
/* eslint-disable */
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_api_v1_common } from "./common_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
/**
 * Describes the file api/v1/audit.proto.
 */
export const file_api_v1_audit = /*@__PURE__*/ fileDesc("ChJhcGkvdjEvYXVkaXQucHJvdG8SBmFwaS52MSKLAgoKQXVkaXRUcmFjZRIWCgR1dWlkGAEgASgJQgi6SAVyA7ABARItCgl0aW1lc3RhbXAYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEgwKBHVzZXIYAyABKAkSDgoGdGVuYW50GAQgASgJEhQKB3Byb2plY3QYBSABKAlIAIgBARIOCgZtZXRob2QYBiABKAkSEQoEYm9keRgHIAEoCUgBiAEBEhEKCXNvdXJjZV9pcBgIIAEoCRIYCgtyZXN1bHRfY29kZRgJIAEoBUgCiAEBEg0KBXBoYXNlGAogASgJQgoKCF9wcm9qZWN0QgcKBV9ib2R5Qg4KDF9yZXN1bHRfY29kZSKKBAoXQXVkaXRTZXJ2aWNlTGlzdFJlcXVlc3QSGQoFbG9naW4YASABKAlCCrpIB3IFEAIYgAESGwoEdXVpZBgCIAEoCUIIukgFcgOwAQFIAIgBARIwCgRmcm9tGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIGukgDyAEBEi4KAnRvGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIGukgDyAEBEh0KBHVzZXIYBSABKAlCCrpIB3IFEAIYgAFIAYgBARIYCgZ0ZW5hbnQYBiABKAlCCLpIBXIDsAEBEh4KB3Byb2plY3QYByABKAlCCLpIBXIDsAEBSAKIAQESHwoGbWV0aG9kGAggASgJQgq6SAdyBRACGIACSAOIAQESHwoJc291cmNlX2lwGAkgASgJQge6SARyAnABSASIAQESIQoLcmVzdWx0X2NvZGUYCiABKAVCB7pIBBoCKABIBYgBARIdCgRib2R5GAsgASgJQgq6SAdyBRACGIACSAaIAQESHgoFbGltaXQYDCABKAVCCrpIBxoFGOgHIABIB4gBAUIHCgVfdXVpZEIHCgVfdXNlckIKCghfcHJvamVjdEIJCgdfbWV0aG9kQgwKCl9zb3VyY2VfaXBCDgoMX3Jlc3VsdF9jb2RlQgcKBV9ib2R5QggKBl9saW1pdCI+ChhBdWRpdFNlcnZpY2VMaXN0UmVzcG9uc2USIgoGYXVkaXRzGAEgAygLMhIuYXBpLnYxLkF1ZGl0VHJhY2UiSwoWQXVkaXRTZXJ2aWNlR2V0UmVxdWVzdBIZCgVsb2dpbhgBIAEoCUIKukgHcgUQAhiAARIWCgR1dWlkGAIgASgJQgi6SAVyA7ABASI8ChdBdWRpdFNlcnZpY2VHZXRSZXNwb25zZRIhCgVhdWRpdBgCIAEoCzISLmFwaS52MS5BdWRpdFRyYWNlMrcBCgxBdWRpdFNlcnZpY2USUQoDR2V0Eh4uYXBpLnYxLkF1ZGl0U2VydmljZUdldFJlcXVlc3QaHy5hcGkudjEuQXVkaXRTZXJ2aWNlR2V0UmVzcG9uc2UiCcLzGAEB6PMYAhJUCgRMaXN0Eh8uYXBpLnYxLkF1ZGl0U2VydmljZUxpc3RSZXF1ZXN0GiAuYXBpLnYxLkF1ZGl0U2VydmljZUxpc3RSZXNwb25zZSIJwvMYAQHo8xgCQoMBCgpjb20uYXBpLnYxQgpBdWRpdFByb3RvUAFaMGdpdGh1Yi5jb20vbWV0YWwtc3RhY2stY2xvdWQvYXBpL2dvL2FwaS92MTthcGl2MaICA0FYWKoCBkFwaS5WMcoCBkFwaVxWMeICEkFwaVxWMVxHUEJNZXRhZGF0YeoCB0FwaTo6VjFiBnByb3RvMw", [file_api_v1_common, file_buf_validate_validate, file_google_protobuf_timestamp]);
/**
 * Describes the message api.v1.AuditTrace.
 * Use `create(AuditTraceSchema)` to create a new message.
 */
export const AuditTraceSchema = /*@__PURE__*/ messageDesc(file_api_v1_audit, 0);
/**
 * Describes the message api.v1.AuditServiceListRequest.
 * Use `create(AuditServiceListRequestSchema)` to create a new message.
 */
export const AuditServiceListRequestSchema = /*@__PURE__*/ messageDesc(file_api_v1_audit, 1);
/**
 * Describes the message api.v1.AuditServiceListResponse.
 * Use `create(AuditServiceListResponseSchema)` to create a new message.
 */
export const AuditServiceListResponseSchema = /*@__PURE__*/ messageDesc(file_api_v1_audit, 2);
/**
 * Describes the message api.v1.AuditServiceGetRequest.
 * Use `create(AuditServiceGetRequestSchema)` to create a new message.
 */
export const AuditServiceGetRequestSchema = /*@__PURE__*/ messageDesc(file_api_v1_audit, 3);
/**
 * Describes the message api.v1.AuditServiceGetResponse.
 * Use `create(AuditServiceGetResponseSchema)` to create a new message.
 */
export const AuditServiceGetResponseSchema = /*@__PURE__*/ messageDesc(file_api_v1_audit, 4);
/**
 * AuditService serves audit related functions
 *
 *
 * @generated from service api.v1.AuditService
 */
export const AuditService = /*@__PURE__*/ serviceDesc(file_api_v1_audit, 0);
