// @generated by protoc-gen-es v1.9.0 with parameter "target=ts"
// @generated from file api/v1/mail.proto (package api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Struct } from "@bufbuild/protobuf";

/**
 * MailType specifies the different mail types we send
 *
 * @generated from enum api.v1.MailType
 */
export enum MailType {
  /**
   * MAIL_TYPE_UNSPECIFIED the mail is unspecified
   *
   * @generated from enum value: MAIL_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * MAIL_TYPE_ADMITTED mail send to users when they are admitted
   *
   * @generated from enum value: MAIL_TYPE_ADMITTED = 1;
   */
  ADMITTED = 1,

  /**
   * MAIL_TYPE_COUPON_PERCENTAGE_USED_WARNING mail send to users when they used a certain amount of their coupon
   *
   * @generated from enum value: MAIL_TYPE_COUPON_PERCENTAGE_USED_WARNING = 2;
   */
  COUPON_PERCENTAGE_USED_WARNING = 2,

  /**
   * MAIL_TYPE_COUPON_COMPLETELY_USED_WARNING mail send to users when the used their coupon completely
   *
   * @generated from enum value: MAIL_TYPE_COUPON_COMPLETELY_USED_WARNING = 3;
   */
  COUPON_COMPLETELY_USED_WARNING = 3,

  /**
   * MAIL_TYPE_PAYMENT_UPDATED mail send to user when he updates the payment information
   *
   * @generated from enum value: MAIL_TYPE_PAYMENT_UPDATED = 4;
   */
  PAYMENT_UPDATED = 4,

  /**
   * MAIL_TYPE_ADMISSION_REQUESTED mail send to support if a user requests the admission
   *
   * @generated from enum value: MAIL_TYPE_ADMISSION_REQUESTED = 5;
   */
  ADMISSION_REQUESTED = 5,

  /**
   * MAIL_TYPE_WELCOME welcome mail if a user registers
   *
   * @generated from enum value: MAIL_TYPE_WELCOME = 6;
   */
  WELCOME = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(MailType)
proto3.util.setEnumType(MailType, "api.v1.MailType", [
  { no: 0, name: "MAIL_TYPE_UNSPECIFIED" },
  { no: 1, name: "MAIL_TYPE_ADMITTED" },
  { no: 2, name: "MAIL_TYPE_COUPON_PERCENTAGE_USED_WARNING" },
  { no: 3, name: "MAIL_TYPE_COUPON_COMPLETELY_USED_WARNING" },
  { no: 4, name: "MAIL_TYPE_PAYMENT_UPDATED" },
  { no: 5, name: "MAIL_TYPE_ADMISSION_REQUESTED" },
  { no: 6, name: "MAIL_TYPE_WELCOME" },
]);

/**
 * MailFunction specifies how a mail should be send
 *
 * @generated from enum api.v1.MailFunction
 */
export enum MailFunction {
  /**
   * MAIL_FUNCTION_UNSPECIFIED the function is unspecified
   *
   * @generated from enum value: MAIL_FUNCTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * MAIL_FUNCTION_SEND send a mail with a message from code
   *
   * @generated from enum value: MAIL_FUNCTION_SEND = 1;
   */
  SEND = 1,

  /**
   * MAIL_FUNCTION_SEND_TEMPLATE send a mail template
   *
   * @generated from enum value: MAIL_FUNCTION_SEND_TEMPLATE = 2;
   */
  SEND_TEMPLATE = 2,

  /**
   * MAIL_FUNCTION_NOTIFY send a mail to our support address
   *
   * @generated from enum value: MAIL_FUNCTION_NOTIFY = 3;
   */
  NOTIFY = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(MailFunction)
proto3.util.setEnumType(MailFunction, "api.v1.MailFunction", [
  { no: 0, name: "MAIL_FUNCTION_UNSPECIFIED" },
  { no: 1, name: "MAIL_FUNCTION_SEND" },
  { no: 2, name: "MAIL_FUNCTION_SEND_TEMPLATE" },
  { no: 3, name: "MAIL_FUNCTION_NOTIFY" },
]);

/**
 * Email is an email we can send from the api-server
 *
 * @generated from message api.v1.Email
 */
export class Email extends Message<Email> {
  /**
   * to is the destination email address(es)
   *
   * @generated from field: repeated string to = 1;
   */
  to: string[] = [];

  /**
   * subject is the the title of the mail
   *
   * @generated from field: optional string subject = 2;
   */
  subject?: string;

  /**
   * mail_type is what mail is send
   *
   * @generated from field: api.v1.MailType mail_type = 3;
   */
  mailType = MailType.UNSPECIFIED;

  /**
   * values is used in templates
   *
   * @generated from field: google.protobuf.Struct values = 4;
   */
  values?: Struct;

  /**
   * msg is used if the mail text is specified directly in code
   *
   * @generated from field: optional string msg = 5;
   */
  msg?: string;

  /**
   * mail_function is how the mail is send
   *
   * @generated from field: api.v1.MailFunction mail_function = 6;
   */
  mailFunction = MailFunction.UNSPECIFIED;

  constructor(data?: PartialMessage<Email>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.v1.Email";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "to", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "mail_type", kind: "enum", T: proto3.getEnumType(MailType) },
    { no: 4, name: "values", kind: "message", T: Struct },
    { no: 5, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "mail_function", kind: "enum", T: proto3.getEnumType(MailFunction) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Email {
    return new Email().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Email {
    return new Email().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Email {
    return new Email().fromJsonString(jsonString, options);
  }

  static equals(a: Email | PlainMessage<Email> | undefined, b: Email | PlainMessage<Email> | undefined): boolean {
    return proto3.util.equals(Email, a, b);
  }
}

