// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file api/v1/version.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_api_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/version.proto.
 */
export const file_api_v1_version: GenFile = /*@__PURE__*/
  fileDesc("ChRhcGkvdjEvdmVyc2lvbi5wcm90bxIGYXBpLnYxIlIKB1ZlcnNpb24SDwoHdmVyc2lvbhgBIAEoCRIQCghyZXZpc2lvbhgCIAEoCRIQCghnaXRfc2hhMRgDIAEoCRISCgpidWlsZF9kYXRlGAQgASgJIhoKGFZlcnNpb25TZXJ2aWNlR2V0UmVxdWVzdCI9ChlWZXJzaW9uU2VydmljZUdldFJlc3BvbnNlEiAKB3ZlcnNpb24YASABKAsyDy5hcGkudjEuVmVyc2lvbjJmCg5WZXJzaW9uU2VydmljZRJUCgNHZXQSIC5hcGkudjEuVmVyc2lvblNlcnZpY2VHZXRSZXF1ZXN0GiEuYXBpLnYxLlZlcnNpb25TZXJ2aWNlR2V0UmVzcG9uc2UiCNjzGAHo8xgCQoUBCgpjb20uYXBpLnYxQgxWZXJzaW9uUHJvdG9QAVowZ2l0aHViLmNvbS9tZXRhbC1zdGFjay1jbG91ZC9hcGkvZ28vYXBpL3YxO2FwaXYxogIDQVhYqgIGQXBpLlYxygIGQXBpXFYx4gISQXBpXFYxXEdQQk1ldGFkYXRh6gIHQXBpOjpWMWIGcHJvdG8z", [file_api_v1_common]);

/**
 * Version of the application
 *
 * @generated from message api.v1.Version
 */
export type Version = Message<"api.v1.Version"> & {
  /**
   * Version of the application
   *
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * Revision of the application
   *
   * @generated from field: string revision = 2;
   */
  revision: string;

  /**
   * GitSHA1 of the application
   *
   * @generated from field: string git_sha1 = 3;
   */
  gitSha1: string;

  /**
   * BuildDate of the application
   *
   * @generated from field: string build_date = 4;
   */
  buildDate: string;
};

/**
 * Describes the message api.v1.Version.
 * Use `create(VersionSchema)` to create a new message.
 */
export const VersionSchema: GenMessage<Version> = /*@__PURE__*/
  messageDesc(file_api_v1_version, 0);

/**
 * VersionServiceGetRequest is the request payload to get the version
 *
 * @generated from message api.v1.VersionServiceGetRequest
 */
export type VersionServiceGetRequest = Message<"api.v1.VersionServiceGetRequest"> & {
};

/**
 * Describes the message api.v1.VersionServiceGetRequest.
 * Use `create(VersionServiceGetRequestSchema)` to create a new message.
 */
export const VersionServiceGetRequestSchema: GenMessage<VersionServiceGetRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_version, 1);

/**
 * VersionServiceGetResponse is the response payload with the version
 *
 * @generated from message api.v1.VersionServiceGetResponse
 */
export type VersionServiceGetResponse = Message<"api.v1.VersionServiceGetResponse"> & {
  /**
   * Version of the application
   *
   * @generated from field: api.v1.Version version = 1;
   */
  version?: Version;
};

/**
 * Describes the message api.v1.VersionServiceGetResponse.
 * Use `create(VersionServiceGetResponseSchema)` to create a new message.
 */
export const VersionServiceGetResponseSchema: GenMessage<VersionServiceGetResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_version, 2);

/**
 * VersionService serves version related functions
 *
 * @generated from service api.v1.VersionService
 */
export const VersionService: GenService<{
  /**
   * Get the version
   *
   * @generated from rpc api.v1.VersionService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof VersionServiceGetRequestSchema;
    output: typeof VersionServiceGetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_version, 0);

