# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from metalstackcloud.admin.v1 import project_pb2 as admin_dot_v1_dot_project__pb2


class ProjectServiceStub(object):
    """ProjectService serves project related functions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/admin.v1.ProjectService/List',
                request_serializer=admin_dot_v1_dot_project__pb2.ProjectServiceListRequest.SerializeToString,
                response_deserializer=admin_dot_v1_dot_project__pb2.ProjectServiceListResponse.FromString,
                _registered_method=True)


class ProjectServiceServicer(object):
    """ProjectService serves project related functions
    """

    def List(self, request, context):
        """List projects based on various filter criteria
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=admin_dot_v1_dot_project__pb2.ProjectServiceListRequest.FromString,
                    response_serializer=admin_dot_v1_dot_project__pb2.ProjectServiceListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.v1.ProjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.v1.ProjectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProjectService(object):
    """ProjectService serves project related functions
    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.v1.ProjectService/List',
            admin_dot_v1_dot_project__pb2.ProjectServiceListRequest.SerializeToString,
            admin_dot_v1_dot_project__pb2.ProjectServiceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
