/**
 * @fileoverview gRPC-Web generated client stub for admin.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v0.0.0
// source: admin/v1/tenant.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var api_v1_common_pb = require('../../api/v1/common_pb.js')

var api_v1_tenant_pb = require('../../api/v1/tenant_pb.js')
const proto = {};
proto.admin = {};
proto.admin.v1 = require('./tenant_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.admin.v1.TenantServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.admin.v1.TenantServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.admin.v1.TenantServiceListRequest,
 *   !proto.admin.v1.TenantServiceListResponse>}
 */
const methodDescriptor_TenantService_List = new grpc.web.MethodDescriptor(
  '/admin.v1.TenantService/List',
  grpc.web.MethodType.UNARY,
  proto.admin.v1.TenantServiceListRequest,
  proto.admin.v1.TenantServiceListResponse,
  /**
   * @param {!proto.admin.v1.TenantServiceListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.admin.v1.TenantServiceListResponse.deserializeBinary
);


/**
 * @param {!proto.admin.v1.TenantServiceListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.admin.v1.TenantServiceListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.admin.v1.TenantServiceListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.admin.v1.TenantServiceClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/admin.v1.TenantService/List',
      request,
      metadata || {},
      methodDescriptor_TenantService_List,
      callback);
};


/**
 * @param {!proto.admin.v1.TenantServiceListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.admin.v1.TenantServiceListResponse>}
 *     Promise that resolves to the response
 */
proto.admin.v1.TenantServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/admin.v1.TenantService/List',
      request,
      metadata || {},
      methodDescriptor_TenantService_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.admin.v1.TenantServiceAdmitRequest,
 *   !proto.admin.v1.TenantServiceAdmitResponse>}
 */
const methodDescriptor_TenantService_Admit = new grpc.web.MethodDescriptor(
  '/admin.v1.TenantService/Admit',
  grpc.web.MethodType.UNARY,
  proto.admin.v1.TenantServiceAdmitRequest,
  proto.admin.v1.TenantServiceAdmitResponse,
  /**
   * @param {!proto.admin.v1.TenantServiceAdmitRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.admin.v1.TenantServiceAdmitResponse.deserializeBinary
);


/**
 * @param {!proto.admin.v1.TenantServiceAdmitRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.admin.v1.TenantServiceAdmitResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.admin.v1.TenantServiceAdmitResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.admin.v1.TenantServiceClient.prototype.admit =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/admin.v1.TenantService/Admit',
      request,
      metadata || {},
      methodDescriptor_TenantService_Admit,
      callback);
};


/**
 * @param {!proto.admin.v1.TenantServiceAdmitRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.admin.v1.TenantServiceAdmitResponse>}
 *     Promise that resolves to the response
 */
proto.admin.v1.TenantServicePromiseClient.prototype.admit =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/admin.v1.TenantService/Admit',
      request,
      metadata || {},
      methodDescriptor_TenantService_Admit);
};


module.exports = proto.admin.v1;

