// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/v1/snapshot.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Snapshot is a unit of block storage create as a point in time block copy of a volume
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uuid is the unique identifier of the snapshot
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Name of the snapshot
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of this snapshot
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Project this snapshot belongs to
	Project string `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	// Partition where this snapshot resides
	Partition string `protobuf:"bytes,5,opt,name=partition,proto3" json:"partition,omitempty"`
	// StorageClass where this snapshot is created
	StorageClass string `protobuf:"bytes,6,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	// Size in bytes of the snapshot
	Size uint64 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// Usage in bytes of the snapshot
	Usage uint64 `protobuf:"varint,8,opt,name=usage,proto3" json:"usage,omitempty"`
	// State of the snapshot
	State string `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	// SourceVolumeUuid is the uuid of the snapshot this snapshot was created from
	SourceVolumeUuid string `protobuf:"bytes,10,opt,name=source_volume_uuid,json=sourceVolumeUuid,proto3" json:"source_volume_uuid,omitempty"`
	// SourceVolumeName is the name of the snapshot this snapshot was created from
	SourceVolumeName string `protobuf:"bytes,11,opt,name=source_volume_name,json=sourceVolumeName,proto3" json:"source_volume_name,omitempty"`
	// ReplicaCount shows how many replicas of this snapshot exist
	ReplicaCount uint32 `protobuf:"varint,12,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"`
	// PrimaryNodeUuid is the uuid of the storage server node where the primary replica of this snapshot resides
	PrimaryNodeUuid string `protobuf:"bytes,13,opt,name=primary_node_uuid,json=primaryNodeUuid,proto3" json:"primary_node_uuid,omitempty"`
	// Retention is the duration after creation, after which this snapshot will be deleted
	Retention *durationpb.Duration `protobuf:"bytes,14,opt,name=retention,proto3" json:"retention,omitempty"`
	// SnapshotStatistics are only visible to admins
	Statistics *SnapshotStatistics `protobuf:"bytes,15,opt,name=statistics,proto3" json:"statistics,omitempty"`
	// CreatedAt is the date when this snapshot was created
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_api_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Snapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Snapshot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Snapshot) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Snapshot) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *Snapshot) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *Snapshot) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Snapshot) GetUsage() uint64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *Snapshot) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Snapshot) GetSourceVolumeUuid() string {
	if x != nil {
		return x.SourceVolumeUuid
	}
	return ""
}

func (x *Snapshot) GetSourceVolumeName() string {
	if x != nil {
		return x.SourceVolumeName
	}
	return ""
}

func (x *Snapshot) GetReplicaCount() uint32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

func (x *Snapshot) GetPrimaryNodeUuid() string {
	if x != nil {
		return x.PrimaryNodeUuid
	}
	return ""
}

func (x *Snapshot) GetRetention() *durationpb.Duration {
	if x != nil {
		return x.Retention
	}
	return nil
}

func (x *Snapshot) GetStatistics() *SnapshotStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *Snapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// SnapshotStatistics are all detailed statistics of a snapshot
type SnapshotStatistics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PhysicalCapacity
	//
	// The physical capacity that exists in this snapshot layer
	PhysicalCapacity uint64 `protobuf:"varint,1,opt,name=physical_capacity,json=physicalCapacity,proto3" json:"physical_capacity,omitempty"`
	// PhysicalOwnedStorageCapacity
	//
	// The capacity that would be freed when snapshot is deleted
	PhysicalOwnedCapacity uint64 `protobuf:"varint,2,opt,name=physical_owned_capacity,json=physicalOwnedCapacity,proto3" json:"physical_owned_capacity,omitempty"`
	// PhysicalOwnedMemory
	//
	// The memory that would be freed when snapshot is deleted
	PhysicalOwnedMemory uint64 `protobuf:"varint,3,opt,name=physical_owned_memory,json=physicalOwnedMemory,proto3" json:"physical_owned_memory,omitempty"`
	// PhysicalMemory
	//
	// The memory that exists for this snapshot
	PhysicalMemory uint64 `protobuf:"varint,4,opt,name=physical_memory,json=physicalMemory,proto3" json:"physical_memory,omitempty"`
	// UserWritten
	//
	// The amount of bytes written to this snapshot by the user
	UserWritten   uint64 `protobuf:"varint,5,opt,name=user_written,json=userWritten,proto3" json:"user_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotStatistics) Reset() {
	*x = SnapshotStatistics{}
	mi := &file_api_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotStatistics) ProtoMessage() {}

func (x *SnapshotStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotStatistics.ProtoReflect.Descriptor instead.
func (*SnapshotStatistics) Descriptor() ([]byte, []int) {
	return file_api_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotStatistics) GetPhysicalCapacity() uint64 {
	if x != nil {
		return x.PhysicalCapacity
	}
	return 0
}

func (x *SnapshotStatistics) GetPhysicalOwnedCapacity() uint64 {
	if x != nil {
		return x.PhysicalOwnedCapacity
	}
	return 0
}

func (x *SnapshotStatistics) GetPhysicalOwnedMemory() uint64 {
	if x != nil {
		return x.PhysicalOwnedMemory
	}
	return 0
}

func (x *SnapshotStatistics) GetPhysicalMemory() uint64 {
	if x != nil {
		return x.PhysicalMemory
	}
	return 0
}

func (x *SnapshotStatistics) GetUserWritten() uint64 {
	if x != nil {
		return x.UserWritten
	}
	return 0
}

// SnapshotServiceGetRequest is the request payload of a snapshot list request
type SnapshotServiceGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uuid of the snapshot
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Project of the snapshot
	Project       string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotServiceGetRequest) Reset() {
	*x = SnapshotServiceGetRequest{}
	mi := &file_api_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotServiceGetRequest) ProtoMessage() {}

func (x *SnapshotServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotServiceGetRequest.ProtoReflect.Descriptor instead.
func (*SnapshotServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotServiceGetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SnapshotServiceGetRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// SnapshotServiceListRequest is the request payload of a snapshot list request
type SnapshotServiceListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uuid of the snapshot
	Uuid *string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	// Project of the snapshot
	Project string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	// Partition where the snapshots should be listed
	Partition *string `protobuf:"bytes,3,opt,name=partition,proto3,oneof" json:"partition,omitempty"`
	// Name of the snapshot
	Name          *string `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotServiceListRequest) Reset() {
	*x = SnapshotServiceListRequest{}
	mi := &file_api_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotServiceListRequest) ProtoMessage() {}

func (x *SnapshotServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotServiceListRequest.ProtoReflect.Descriptor instead.
func (*SnapshotServiceListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotServiceListRequest) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *SnapshotServiceListRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SnapshotServiceListRequest) GetPartition() string {
	if x != nil && x.Partition != nil {
		return *x.Partition
	}
	return ""
}

func (x *SnapshotServiceListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// SnapshotServiceDeleteRequest is the request payload of a snapshot delete request
type SnapshotServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uuid of the snapshot
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Project of the snapshot
	Project       string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotServiceDeleteRequest) Reset() {
	*x = SnapshotServiceDeleteRequest{}
	mi := &file_api_v1_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotServiceDeleteRequest) ProtoMessage() {}

func (x *SnapshotServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*SnapshotServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotServiceDeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SnapshotServiceDeleteRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// SnapshotServiceGetResponse is the response payload of a snapshot get request
type SnapshotServiceGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot the snapshot
	Snapshot      *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotServiceGetResponse) Reset() {
	*x = SnapshotServiceGetResponse{}
	mi := &file_api_v1_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotServiceGetResponse) ProtoMessage() {}

func (x *SnapshotServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotServiceGetResponse.ProtoReflect.Descriptor instead.
func (*SnapshotServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotServiceGetResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// SnapshotServiceListResponse is the response payload of a snapshot list request
type SnapshotServiceListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshots the snapshots
	Snapshots     []*Snapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotServiceListResponse) Reset() {
	*x = SnapshotServiceListResponse{}
	mi := &file_api_v1_snapshot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotServiceListResponse) ProtoMessage() {}

func (x *SnapshotServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_snapshot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotServiceListResponse.ProtoReflect.Descriptor instead.
func (*SnapshotServiceListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotServiceListResponse) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// SnapshotServiceDeleteResponse is the response payload of a snapshot delete request
type SnapshotServiceDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot the snapshot
	Snapshot      *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotServiceDeleteResponse) Reset() {
	*x = SnapshotServiceDeleteResponse{}
	mi := &file_api_v1_snapshot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotServiceDeleteResponse) ProtoMessage() {}

func (x *SnapshotServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_snapshot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*SnapshotServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotServiceDeleteResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_api_v1_snapshot_proto protoreflect.FileDescriptor

const file_api_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/snapshot.proto\x12\x06api.v1\x1a\x13api/v1/common.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x04\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aproject\x18\x04 \x01(\tR\aproject\x12\x1c\n" +
	"\tpartition\x18\x05 \x01(\tR\tpartition\x12#\n" +
	"\rstorage_class\x18\x06 \x01(\tR\fstorageClass\x12\x12\n" +
	"\x04size\x18\a \x01(\x04R\x04size\x12\x14\n" +
	"\x05usage\x18\b \x01(\x04R\x05usage\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12,\n" +
	"\x12source_volume_uuid\x18\n" +
	" \x01(\tR\x10sourceVolumeUuid\x12,\n" +
	"\x12source_volume_name\x18\v \x01(\tR\x10sourceVolumeName\x12#\n" +
	"\rreplica_count\x18\f \x01(\rR\freplicaCount\x12*\n" +
	"\x11primary_node_uuid\x18\r \x01(\tR\x0fprimaryNodeUuid\x127\n" +
	"\tretention\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\tretention\x12:\n" +
	"\n" +
	"statistics\x18\x0f \x01(\v2\x1a.api.v1.SnapshotStatisticsR\n" +
	"statistics\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf9\x01\n" +
	"\x12SnapshotStatistics\x12+\n" +
	"\x11physical_capacity\x18\x01 \x01(\x04R\x10physicalCapacity\x126\n" +
	"\x17physical_owned_capacity\x18\x02 \x01(\x04R\x15physicalOwnedCapacity\x122\n" +
	"\x15physical_owned_memory\x18\x03 \x01(\x04R\x13physicalOwnedMemory\x12'\n" +
	"\x0fphysical_memory\x18\x04 \x01(\x04R\x0ephysicalMemory\x12!\n" +
	"\fuser_written\x18\x05 \x01(\x04R\vuserWritten\"_\n" +
	"\x19SnapshotServiceGetRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\x12$\n" +
	"\aproject\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x01R\aproject\"\xc1\x01\n" +
	"\x1aSnapshotServiceListRequest\x12!\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x04uuid\x88\x01\x01\x12$\n" +
	"\aproject\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x01R\aproject\x12!\n" +
	"\tpartition\x18\x03 \x01(\tH\x01R\tpartition\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x02R\x04name\x88\x01\x01B\a\n" +
	"\x05_uuidB\f\n" +
	"\n" +
	"_partitionB\a\n" +
	"\x05_name\"b\n" +
	"\x1cSnapshotServiceDeleteRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\x12$\n" +
	"\aproject\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x01R\aproject\"J\n" +
	"\x1aSnapshotServiceGetResponse\x12,\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x10.api.v1.SnapshotR\bsnapshot\"M\n" +
	"\x1bSnapshotServiceListResponse\x12.\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x10.api.v1.SnapshotR\tsnapshots\"M\n" +
	"\x1dSnapshotServiceDeleteResponse\x12,\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x10.api.v1.SnapshotR\bsnapshot2\xa9\x02\n" +
	"\x0fSnapshotService\x12Y\n" +
	"\x03Get\x12!.api.v1.SnapshotServiceGetRequest\x1a\".api.v1.SnapshotServiceGetResponse\"\v\xca\xf3\x18\x03\x01\x02\x03\xe8\xf3\x18\x02\x12\\\n" +
	"\x04List\x12\".api.v1.SnapshotServiceListRequest\x1a#.api.v1.SnapshotServiceListResponse\"\v\xca\xf3\x18\x03\x01\x02\x03\xe8\xf3\x18\x02\x12]\n" +
	"\x06Delete\x12$.api.v1.SnapshotServiceDeleteRequest\x1a%.api.v1.SnapshotServiceDeleteResponse\"\x06\xca\xf3\x18\x02\x01\x02B\x86\x01\n" +
	"\n" +
	"com.api.v1B\rSnapshotProtoP\x01Z0github.com/metal-stack-cloud/api/go/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_snapshot_proto_rawDescOnce sync.Once
	file_api_v1_snapshot_proto_rawDescData []byte
)

func file_api_v1_snapshot_proto_rawDescGZIP() []byte {
	file_api_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_api_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_snapshot_proto_rawDesc), len(file_api_v1_snapshot_proto_rawDesc)))
	})
	return file_api_v1_snapshot_proto_rawDescData
}

var file_api_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_snapshot_proto_goTypes = []any{
	(*Snapshot)(nil),                      // 0: api.v1.Snapshot
	(*SnapshotStatistics)(nil),            // 1: api.v1.SnapshotStatistics
	(*SnapshotServiceGetRequest)(nil),     // 2: api.v1.SnapshotServiceGetRequest
	(*SnapshotServiceListRequest)(nil),    // 3: api.v1.SnapshotServiceListRequest
	(*SnapshotServiceDeleteRequest)(nil),  // 4: api.v1.SnapshotServiceDeleteRequest
	(*SnapshotServiceGetResponse)(nil),    // 5: api.v1.SnapshotServiceGetResponse
	(*SnapshotServiceListResponse)(nil),   // 6: api.v1.SnapshotServiceListResponse
	(*SnapshotServiceDeleteResponse)(nil), // 7: api.v1.SnapshotServiceDeleteResponse
	(*durationpb.Duration)(nil),           // 8: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
}
var file_api_v1_snapshot_proto_depIdxs = []int32{
	8, // 0: api.v1.Snapshot.retention:type_name -> google.protobuf.Duration
	1, // 1: api.v1.Snapshot.statistics:type_name -> api.v1.SnapshotStatistics
	9, // 2: api.v1.Snapshot.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: api.v1.SnapshotServiceGetResponse.snapshot:type_name -> api.v1.Snapshot
	0, // 4: api.v1.SnapshotServiceListResponse.snapshots:type_name -> api.v1.Snapshot
	0, // 5: api.v1.SnapshotServiceDeleteResponse.snapshot:type_name -> api.v1.Snapshot
	2, // 6: api.v1.SnapshotService.Get:input_type -> api.v1.SnapshotServiceGetRequest
	3, // 7: api.v1.SnapshotService.List:input_type -> api.v1.SnapshotServiceListRequest
	4, // 8: api.v1.SnapshotService.Delete:input_type -> api.v1.SnapshotServiceDeleteRequest
	5, // 9: api.v1.SnapshotService.Get:output_type -> api.v1.SnapshotServiceGetResponse
	6, // 10: api.v1.SnapshotService.List:output_type -> api.v1.SnapshotServiceListResponse
	7, // 11: api.v1.SnapshotService.Delete:output_type -> api.v1.SnapshotServiceDeleteResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_snapshot_proto_init() }
func file_api_v1_snapshot_proto_init() {
	if File_api_v1_snapshot_proto != nil {
		return
	}
	file_api_v1_common_proto_init()
	file_api_v1_snapshot_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_snapshot_proto_rawDesc), len(file_api_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_api_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_api_v1_snapshot_proto_msgTypes,
	}.Build()
	File_api_v1_snapshot_proto = out.File
	file_api_v1_snapshot_proto_goTypes = nil
	file_api_v1_snapshot_proto_depIdxs = nil
}
