// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"connectrpc.com/connect"
	"github.com/metal-stack-cloud/api/go/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMethodServiceClient creates a new instance of MethodServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMethodServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MethodServiceClient {
	mock := &MethodServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MethodServiceClient is an autogenerated mock type for the MethodServiceClient type
type MethodServiceClient struct {
	mock.Mock
}

type MethodServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MethodServiceClient) EXPECT() *MethodServiceClient_Expecter {
	return &MethodServiceClient_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MethodServiceClient
func (_mock *MethodServiceClient) List(context1 context.Context, request *connect.Request[apiv1.MethodServiceListRequest]) (*connect.Response[apiv1.MethodServiceListResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *connect.Response[apiv1.MethodServiceListResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[apiv1.MethodServiceListRequest]) (*connect.Response[apiv1.MethodServiceListResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[apiv1.MethodServiceListRequest]) *connect.Response[apiv1.MethodServiceListResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[apiv1.MethodServiceListResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[apiv1.MethodServiceListRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MethodServiceClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MethodServiceClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[apiv1.MethodServiceListRequest]
func (_e *MethodServiceClient_Expecter) List(context1 interface{}, request interface{}) *MethodServiceClient_List_Call {
	return &MethodServiceClient_List_Call{Call: _e.mock.On("List", context1, request)}
}

func (_c *MethodServiceClient_List_Call) Run(run func(context1 context.Context, request *connect.Request[apiv1.MethodServiceListRequest])) *MethodServiceClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[apiv1.MethodServiceListRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[apiv1.MethodServiceListRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MethodServiceClient_List_Call) Return(response *connect.Response[apiv1.MethodServiceListResponse], err error) *MethodServiceClient_List_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MethodServiceClient_List_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[apiv1.MethodServiceListRequest]) (*connect.Response[apiv1.MethodServiceListResponse], error)) *MethodServiceClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// TokenScopedList provides a mock function for the type MethodServiceClient
func (_mock *MethodServiceClient) TokenScopedList(context1 context.Context, request *connect.Request[apiv1.MethodServiceTokenScopedListRequest]) (*connect.Response[apiv1.MethodServiceTokenScopedListResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for TokenScopedList")
	}

	var r0 *connect.Response[apiv1.MethodServiceTokenScopedListResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[apiv1.MethodServiceTokenScopedListRequest]) (*connect.Response[apiv1.MethodServiceTokenScopedListResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[apiv1.MethodServiceTokenScopedListRequest]) *connect.Response[apiv1.MethodServiceTokenScopedListResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[apiv1.MethodServiceTokenScopedListResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[apiv1.MethodServiceTokenScopedListRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MethodServiceClient_TokenScopedList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenScopedList'
type MethodServiceClient_TokenScopedList_Call struct {
	*mock.Call
}

// TokenScopedList is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[apiv1.MethodServiceTokenScopedListRequest]
func (_e *MethodServiceClient_Expecter) TokenScopedList(context1 interface{}, request interface{}) *MethodServiceClient_TokenScopedList_Call {
	return &MethodServiceClient_TokenScopedList_Call{Call: _e.mock.On("TokenScopedList", context1, request)}
}

func (_c *MethodServiceClient_TokenScopedList_Call) Run(run func(context1 context.Context, request *connect.Request[apiv1.MethodServiceTokenScopedListRequest])) *MethodServiceClient_TokenScopedList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[apiv1.MethodServiceTokenScopedListRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[apiv1.MethodServiceTokenScopedListRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MethodServiceClient_TokenScopedList_Call) Return(response *connect.Response[apiv1.MethodServiceTokenScopedListResponse], err error) *MethodServiceClient_TokenScopedList_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MethodServiceClient_TokenScopedList_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[apiv1.MethodServiceTokenScopedListRequest]) (*connect.Response[apiv1.MethodServiceTokenScopedListResponse], error)) *MethodServiceClient_TokenScopedList_Call {
	_c.Call.Return(run)
	return _c
}
