name: build
on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: -p bugs -p unused -D protogetter --timeout=3m

    - name: build and push npm package
      uses: oven-sh/setup-bun@v1

    - run: |
        cd js
        bun install typescript
        bun install
    - uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
        access: public
        package: js/package.json
