name: build
on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: -p bugs -p unused -D protogetter --timeout=5m

    - name: Build
      run: |
        if ! which yq; then
          sudo curl -Lo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
        fi
        make release

    - name: build and push npm package
      uses: actions/setup-node@v3
      with:
        scope: '@metal-stack-cloud'
      if: github.event_name == 'release'

    - run: |
        cd js
        npm install typescript
        npm install
      if: github.event_name == 'release'

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
        access: public
        package: js/package.json
      if: github.event_name == 'release'
