name: pull request
on: 
  pull_request:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: -p bugs -p unused -D protogetter --timeout=3m

    - name: test
      run: |
        make

